services:
  asterisk:
    build: ./asterisk
    restart: unless-stopped
    env_file: .env
    network_mode: host
    depends_on:
      - app

  app:
    build: ./app
    restart: unless-stopped
    env_file: .env
    network_mode: host
