[modules]
autoload=yes
noload => chan_sip.so
load => res_pjsip.so
load => res_pjsip_transport_udp.so
load => res_pjsip_outbound_registration.so
load => app_audiosocket.so
load => codec_ulaw.so
load => codec_alaw.so
load => codec_resample.so
